name: Feature Test
on:
  push:
    branches:
      - feature/**
env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
jobs:
  validate_feature:
    name: "Validate Feature"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Write the token into a file
        run: 'echo ${{secrets.DEVHUB_TOKEN}} > token.txt'
      - name: Install sfdx
        run: "npm install sfdx-cli --global"
      - name: Auth with the DevHub
        run: 'sfdx force:auth:sfdxurl:store -f token.txt -a DevHub -d'
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - name: Create Dev Scratch Org
        run: |
          cci flow run dev_org --org dev
      - name: Run Unit Tests
        run: |
          cci task run run_tests --org dev
      - name: Delete Scratch Org
        if: ${{ always() }}
        run: |
          cci org scratch_delete dev
