name: Package Build
on:
  push:
    branches:
      - master
env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
jobs:
  beta_test:
    name: "Create Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Write the token into a file
        run: 'echo ${{secrets.DEVHUB_TOKEN}} > token.txt'
      - name: Install sfdx
        run: "npm install sfdx-cli --global"
      - name: Auth with the DevHub
        run: 'sfdx force:auth:sfdxurl:store -f token.txt -a DevHub -d'
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - name: Create Scratch Org and Run Unit Tests
        run: |
          cci flow run ci_beta --org beta
      - name: Create Package Version
        run: |
          cci flow run release_unlocked_beta --org beta
      - name: Release Beta
        run: |
          cci flow run release_unlocked_production --org release
          cci task run github_automerge_main
      - name: Delete Scratch Orgs
        if: ${{ always() }}
        run: |
          cci org scratch_delete beta
          cci org scratch_delete release
